### ISSUE TITLE
Nil checking on observations#direction

### ISSUE THREAD

**Issue by maxcal** [remote-wind/remote-wind#158]
The production server is running into issues when serializing some of the observations from the node-red stations since they are missing the direction attribute. 

```
2016-11-03T22:29:28.982723+00:00 heroku[router]: at=info method=GET path="/stations/smhi_nordkoster_a/observations" host=www.blast.nu request_id=832b125a-0e4e-4a6b-8b88-e2fc67278391 fwd="85.227.232.184" dyno=web.1 connect=1ms service=135ms status=500 bytes=245
2016-11-03T22:29:28.833920+00:00 app[web.1]: Started GET "/stations/smhi_nordkoster_a/observations" for 85.227.232.184 at 2016-11-03 22:29:28 +0000
2016-11-03T22:29:28.836875+00:00 app[web.1]: Processing by ObservationsController#index as JSON
2016-11-03T22:29:28.836939+00:00 app[web.1]:   Parameters: {"station_id"=>"smhi_nordkoster_a"}
2016-11-03T22:29:28.843978+00:00 app[web.1]: Started GET "/stations.json" for 85.227.232.184 at 2016-11-03 22:29:28 +0000
2016-11-03T22:29:28.848880+00:00 app[web.1]: Processing by StationsController#index as JSON
2016-11-03T22:29:28.855837+00:00 app[web.1]: Completed 304 Not Modified in 7ms (ActiveRecord: 1.0ms)
2016-11-03T22:29:28.965258+00:00 app[web.1]: Completed 500 Internal Server Error in 128ms (ActiveRecord: 9.9ms)
2016-11-03T22:29:28.966934+00:00 app[web.1]: 
2016-11-03T22:29:28.966935+00:00 app[web.1]: NoMethodError (undefined method `+' for nil:NilClass):
2016-11-03T22:29:28.966936+00:00 app[web.1]:   app/models/observation.rb:59:in `compass_point'
2016-11-03T22:29:28.966937+00:00 app[web.1]:   app/serializers/observation_serializer.rb:6:in `attributes'
2016-11-03T22:29:28.966938+00:00 app[web.1]:   app/controllers/observations_controller.rb:46:in `block (2 levels) in index'
2016-11-03T22:29:28.966938+00:00 app[web.1]:   app/controllers/observations_controller.rb:35:in `index'
```

**Comment by maxcal** [comment]
The validations on observations are pretty lax and will allow blank values.

**Comment by karl-petter** [comment]
hmm, strange. but will also check the code on the node-red nodes. I'll plan to put those in a repo as well so people can make their own. Just need the time.

**Comment by karl-petter** [comment]
Added check in ac45e6df92b2d2e8df01372e2c7845deee1e9ce6
